### ISSUE TITLE
calabash code sign repo doesn't exist

### ISSUE THREAD

**Issue by kpranavk** [calabash/iOSDeviceManager#252]
Under Code signing it says "Project maintainers must clone the codesign repo and install the certs and profiles". However the target link https://github.com/calabash/calabash-codesign doesn't exist.

1. If the repo does exist somewhere, please update the documentation with the new URL
2. If the repo doesn't exist, please provide documentation on how to build with the valid certs and profiles.

**Comment by jmoody** [comment]
The repo is private.

You need to update the code signing properties in the Xcode project to match the certs/profiles on your computer.

**Comment by jmoody** [comment]
As to your second point:

> Contributors need to touch the Xcode project file with valid credentials.

I have updated this to:

 > Contributors will need to update the Xcode project with valid code signing properties.
