### ISSUE TITLE
 iOSDeviceManager fails to run

### ISSUE THREAD

**Issue by john7doe** [calabash/iOSDeviceManager#269]
Using Visual Studio for Mac 8.5 (Build) on MacOS 10.15.3 I get this dialog if I try to run a Xamarin.UITest from within the IDE:

<img width="433" alt="Screenshot 2020-03-25 at 14 30 12" src="https://user-images.githubusercontent.com/433840/77550899-e9437380-6eb1-11ea-9b17-8c8e30654509.png">

**Comment by jmoody** [comment]
The problem was that the iOSDeviceManager certificate had been revoked.

Updating to the latest Xamarin.UITest fixes this problem.

**Comment by abxhanno** [comment]
With the brand new Xamarin.UITest 4.3.3 Update the iOSDeviceManager was replaced by Facebook's idb

`Replaced iOSDeviceManager usage with Facebook's idb. To use idb you will need to install it with brew on target system. idb-companion is not needed`

A new challenge is the installation of the idb and letting Visual Studio know where to find the idb installation (unfortunately Visual Studio ignores the global PATH declarations). Anyway now we are able to perform UI Tests on iOS 17 simulators again. But UI Tests on IOS < 17 seems to be very unstable (?).
